"""add constraintes to creation agent

Revision ID: a2145fa04639
Revises: e929990ac646
Create Date: 2025-02-09 23:56:04.762970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2145fa04639'
down_revision = 'e929990ac646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_agents', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_agents', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
